# Generated by Django 3.2.5 on 2021-07-28 22:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('birdness', models.IntegerField(max_length=1)),
                ('usefulness', models.IntegerField(max_length=1)),
                ('enjoyability', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('department', models.CharField(max_length=20)),
                ('score', models.FloatField()),
                ('mean_grade', models.FloatField()),
                ('rating_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wlugo_app.rating')),
            ],
        ),
    ]
